CREATE TABLE IF NOT EXISTS node_disk_info (
  id SERIAL PRIMARY KEY,
  node_id INTEGER NOT NULL,
  device TEXT,
  mount_point TEXT,
  fstype TEXT,
  total float,
  used float,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);