CREATE TABLE IF NOT EXISTS nodes (
  id SERIAL PRIMARY KEY,
  name TEXT,
  ip TEXT NOT NULL UNIQUE,
  cpu_cores INTEGER,
  cpu_ghz REAL , -- GHz per core
  memory INTEGER, -- in MB
  disk INTEGER , -- in GB
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);