// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	activateAlertStmt                  *sql.Stmt
	addNodeDiskInfoStmt                *sql.Stmt
	addNodeSysInfoStmt                 *sql.Stmt
	createAlertStmt                    *sql.Stmt
	createNodeStmt                     *sql.Stmt
	createUserStmt                     *sql.Stmt
	deactivateAlertStmt                *sql.Stmt
	deleteAlertStmt                    *sql.Stmt
	deleteNodeStmt                     *sql.Stmt
	findUserByEmailStmt                *sql.Stmt
	findUserByIdStmt                   *sql.Stmt
	getActiveAlertsByNodeAndMetricStmt *sql.Stmt
	getAlertStmt                       *sql.Stmt
	getAlertsStmt                      *sql.Stmt
	getNetStatsStmt                    *sql.Stmt
	getNodeStmt                        *sql.Stmt
	getNodeByIPStmt                    *sql.Stmt
	getNodeDiskInfoByNodeIDStmt        *sql.Stmt
	getNodeSysInfoByNodeIDStmt         *sql.Stmt
	getNodeWithSysInfoStmt             *sql.Stmt
	getNodesStmt                       *sql.Stmt
	getNodesWithSysInfoStmt            *sql.Stmt
	getSystemStatsStmt                 *sql.Stmt
	insertNetStatsStmt                 *sql.Stmt
	insertSystemStatsStmt              *sql.Stmt
	updateAlertStmt                    *sql.Stmt
	updateNodeStmt                     *sql.Stmt
	updateNodeDiskInfoStmt             *sql.Stmt
	updateNodeNameStmt                 *sql.Stmt
	updateNodeSysInfoStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		activateAlertStmt:                  q.activateAlertStmt,
		addNodeDiskInfoStmt:                q.addNodeDiskInfoStmt,
		addNodeSysInfoStmt:                 q.addNodeSysInfoStmt,
		createAlertStmt:                    q.createAlertStmt,
		createNodeStmt:                     q.createNodeStmt,
		createUserStmt:                     q.createUserStmt,
		deactivateAlertStmt:                q.deactivateAlertStmt,
		deleteAlertStmt:                    q.deleteAlertStmt,
		deleteNodeStmt:                     q.deleteNodeStmt,
		findUserByEmailStmt:                q.findUserByEmailStmt,
		findUserByIdStmt:                   q.findUserByIdStmt,
		getActiveAlertsByNodeAndMetricStmt: q.getActiveAlertsByNodeAndMetricStmt,
		getAlertStmt:                       q.getAlertStmt,
		getAlertsStmt:                      q.getAlertsStmt,
		getNetStatsStmt:                    q.getNetStatsStmt,
		getNodeStmt:                        q.getNodeStmt,
		getNodeByIPStmt:                    q.getNodeByIPStmt,
		getNodeDiskInfoByNodeIDStmt:        q.getNodeDiskInfoByNodeIDStmt,
		getNodeSysInfoByNodeIDStmt:         q.getNodeSysInfoByNodeIDStmt,
		getNodeWithSysInfoStmt:             q.getNodeWithSysInfoStmt,
		getNodesStmt:                       q.getNodesStmt,
		getNodesWithSysInfoStmt:            q.getNodesWithSysInfoStmt,
		getSystemStatsStmt:                 q.getSystemStatsStmt,
		insertNetStatsStmt:                 q.insertNetStatsStmt,
		insertSystemStatsStmt:              q.insertSystemStatsStmt,
		updateAlertStmt:                    q.updateAlertStmt,
		updateNodeStmt:                     q.updateNodeStmt,
		updateNodeDiskInfoStmt:             q.updateNodeDiskInfoStmt,
		updateNodeNameStmt:                 q.updateNodeNameStmt,
		updateNodeSysInfoStmt:              q.updateNodeSysInfoStmt,
	}
}
