// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Alert struct {
	ID               int64           `json:"id"`
	NodeID           int64           `json:"node_id"`
	Metric           string          `json:"metric"`
	Duration         int64           `json:"duration"`
	Threshold        sql.NullFloat64 `json:"threshold"`
	NetReceThreshold sql.NullFloat64 `json:"net_rece_threshold"`
	NetSendThreshold sql.NullFloat64 `json:"net_send_threshold"`
	Email            sql.NullString  `json:"email"`
	DiscordWebhook   sql.NullString  `json:"discord_webhook"`
	SlackWebhook     sql.NullString  `json:"slack_webhook"`
	IsActive         sql.NullInt64   `json:"is_active"`
	CreatedAt        int64           `json:"created_at"`
	UpdatedAt        int64           `json:"updated_at"`
}

type NetStat struct {
	Timestamp int64 `json:"timestamp"`
	NodeID    int64 `json:"node_id"`
	Sent      int64 `json:"sent"`
	Recv      int64 `json:"recv"`
}

type Node struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Ip        string         `json:"ip"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type NodeDiskInfo struct {
	ID         int64           `json:"id"`
	NodeID     int64           `json:"node_id"`
	Device     sql.NullString  `json:"device"`
	MountPoint sql.NullString  `json:"mount_point"`
	Fstype     sql.NullString  `json:"fstype"`
	Total      sql.NullFloat64 `json:"total"`
	Used       sql.NullFloat64 `json:"used"`
	CreatedAt  int64           `json:"created_at"`
	UpdatedAt  int64           `json:"updated_at"`
}

type NodeSysInfo struct {
	ID              int64           `json:"id"`
	NodeID          int64           `json:"node_id"`
	Os              sql.NullString  `json:"os"`
	Platform        sql.NullString  `json:"platform"`
	PlatformVersion sql.NullString  `json:"platform_version"`
	KernelVersion   sql.NullString  `json:"kernel_version"`
	Cpus            sql.NullInt64   `json:"cpus"`
	TotalMemory     sql.NullFloat64 `json:"total_memory"`
	CreatedAt       int64           `json:"created_at"`
	UpdatedAt       int64           `json:"updated_at"`
}

type Project struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	NodeID         int64          `json:"node_id"`
	RepoUrl        sql.NullString `json:"repo_url"`
	Branch         sql.NullString `json:"branch"`
	DeployPath     string         `json:"deploy_path"`
	Status         sql.NullString `json:"status"`
	LastDeployedAt sql.NullInt64  `json:"last_deployed_at"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type SystemStat struct {
	Timestamp int64         `json:"timestamp"`
	NodeID    int64         `json:"node_id"`
	StatType  string        `json:"stat_type"`
	CpuID     sql.NullInt64 `json:"cpu_id"`
	Value     float64       `json:"value"`
}

type User struct {
	ID           int64         `json:"id"`
	Username     string        `json:"username"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	CreatedAt    sql.NullInt64 `json:"created_at"`
	UpdatedAt    sql.NullInt64 `json:"updated_at"`
}
