// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: net_stat.sql

package db

import (
	"context"
)

const getNetStats = `-- name: GetNetStats :many
select timestamp, sent, recv from net_stat ns
where node_id = ?
and timestamp >= strftime('%s', 'now') - ?
`

type GetNetStatsParams struct {
	NodeID  int64       `json:"node_id"`
	Column2 interface{} `json:"column_2"`
}

type GetNetStatsRow struct {
	Timestamp int64 `json:"timestamp"`
	Sent      int64 `json:"sent"`
	Recv      int64 `json:"recv"`
}

func (q *Queries) GetNetStats(ctx context.Context, arg GetNetStatsParams) ([]GetNetStatsRow, error) {
	rows, err := q.query(ctx, q.getNetStatsStmt, getNetStats, arg.NodeID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNetStatsRow
	for rows.Next() {
		var i GetNetStatsRow
		if err := rows.Scan(&i.Timestamp, &i.Sent, &i.Recv); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNetStats = `-- name: InsertNetStats :exec
INSERT INTO net_stat (timestamp, node_id, sent, recv) VALUES (?, ?, ?, ?)
`

type InsertNetStatsParams struct {
	Timestamp int64 `json:"timestamp"`
	NodeID    int64 `json:"node_id"`
	Sent      int64 `json:"sent"`
	Recv      int64 `json:"recv"`
}

func (q *Queries) InsertNetStats(ctx context.Context, arg InsertNetStatsParams) error {
	_, err := q.exec(ctx, q.insertNetStatsStmt, insertNetStats,
		arg.Timestamp,
		arg.NodeID,
		arg.Sent,
		arg.Recv,
	)
	return err
}
