// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (node_id, name, path, tech, commands, logs, backups, discovered_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
ON CONFLICT (node_id, path) DO UPDATE SET
    name       = excluded.name,
    tech       = excluded.tech,
    commands   = excluded.commands,
    logs       = excluded.logs,
    backups    = excluded.backups,
    updated_at = strftime('%s', 'now')
RETURNING id, node_id, name, path, tech, commands, logs, backups, discovered_at, updated_at
`

type UpsertProjectParams struct {
	NodeID   int64  `json:"node_id"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	Tech     string `json:"tech"`
	Commands string `json:"commands"`
	Logs     string `json:"logs"`
	Backups  string `json:"backups"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.upsertProjectStmt, upsertProject,
		arg.NodeID,
		arg.Name,
		arg.Path,
		arg.Tech,
		arg.Commands,
		arg.Logs,
		arg.Backups,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Path,
		&i.Tech,
		&i.Commands,
		&i.Logs,
		&i.Backups,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, node_id, name, path, tech, commands, logs, backups, discovered_at, updated_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectStmt, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Path,
		&i.Tech,
		&i.Commands,
		&i.Logs,
		&i.Backups,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectWithNode = `-- name: GetProjectWithNode :one
SELECT
    p.id, p.node_id, p.name, p.path, p.tech, p.commands, p.logs, p.backups, p.discovered_at, p.updated_at,
    n.name AS node_name,
    n.ip   AS node_ip
FROM projects p
LEFT JOIN nodes n ON p.node_id = n.id
WHERE p.id = ?
`

type GetProjectWithNodeRow struct {
	ID           string         `json:"id"`
	NodeID       int64          `json:"node_id"`
	Name         string         `json:"name"`
	Path         string         `json:"path"`
	Tech         string         `json:"tech"`
	Commands     string         `json:"commands"`
	Logs         string         `json:"logs"`
	Backups      string         `json:"backups"`
	DiscoveredAt int64          `json:"discovered_at"`
	UpdatedAt    int64          `json:"updated_at"`
	NodeName     sql.NullString `json:"node_name"`
	NodeIp       sql.NullString `json:"node_ip"`
}

func (q *Queries) GetProjectWithNode(ctx context.Context, id string) (GetProjectWithNodeRow, error) {
	row := q.queryRow(ctx, q.getProjectWithNodeStmt, getProjectWithNode, id)
	var i GetProjectWithNodeRow
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Path,
		&i.Tech,
		&i.Commands,
		&i.Logs,
		&i.Backups,
		&i.DiscoveredAt,
		&i.UpdatedAt,
		&i.NodeName,
		&i.NodeIp,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, node_id, name, path, tech, commands, logs, backups, discovered_at, updated_at
FROM projects
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsStmt, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Path,
			&i.Tech,
			&i.Commands,
			&i.Logs,
			&i.Backups,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByNode = `-- name: ListProjectsByNode :many
SELECT id, node_id, name, path, tech, commands, logs, backups, discovered_at, updated_at
FROM projects
WHERE node_id = ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsByNodeParams struct {
	NodeID int64 `json:"node_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjectsByNode(ctx context.Context, arg ListProjectsByNodeParams) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsByNodeStmt, listProjectsByNode, arg.NodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Path,
			&i.Tech,
			&i.Commands,
			&i.Logs,
			&i.Backups,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithNodes = `-- name: ListProjectsWithNodes :many
SELECT
    p.id, p.node_id, p.name, p.path, p.tech, p.commands, p.logs, p.backups, p.discovered_at, p.updated_at,
    n.name AS node_name,
    n.ip   AS node_ip
FROM projects p
LEFT JOIN nodes n ON p.node_id = n.id
ORDER BY p.updated_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsWithNodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProjectsWithNodesRow struct {
	ID           string         `json:"id"`
	NodeID       int64          `json:"node_id"`
	Name         string         `json:"name"`
	Path         string         `json:"path"`
	Tech         string         `json:"tech"`
	Commands     string         `json:"commands"`
	Logs         string         `json:"logs"`
	Backups      string         `json:"backups"`
	DiscoveredAt int64          `json:"discovered_at"`
	UpdatedAt    int64          `json:"updated_at"`
	NodeName     sql.NullString `json:"node_name"`
	NodeIp       sql.NullString `json:"node_ip"`
}

func (q *Queries) ListProjectsWithNodes(ctx context.Context, arg ListProjectsWithNodesParams) ([]ListProjectsWithNodesRow, error) {
	rows, err := q.query(ctx, q.listProjectsWithNodesStmt, listProjectsWithNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsWithNodesRow
	for rows.Next() {
		var i ListProjectsWithNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Path,
			&i.Tech,
			&i.Commands,
			&i.Logs,
			&i.Backups,
			&i.DiscoveredAt,
			&i.UpdatedAt,
			&i.NodeName,
			&i.NodeIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteProjectStmt, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProjectsByNode = `-- name: DeleteProjectsByNode :execrows
DELETE FROM projects WHERE node_id = ?
`

func (q *Queries) DeleteProjectsByNode(ctx context.Context, nodeID int64) (int64, error) {
	result, err := q.exec(ctx, q.deleteProjectsByNodeStmt, deleteProjectsByNode, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countProjectsStmt, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByNode = `-- name: CountProjectsByNode :one
SELECT COUNT(*) FROM projects WHERE node_id = ?
`

func (q *Queries) CountProjectsByNode(ctx context.Context, nodeID int64) (int64, error) {
	row := q.queryRow(ctx, q.countProjectsByNodeStmt, countProjectsByNode, nodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
