// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countProjectsStmt, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByNode = `-- name: CountProjectsByNode :one
SELECT COUNT(*) FROM projects WHERE node_id = ?
`

func (q *Queries) CountProjectsByNode(ctx context.Context, nodeID int64) (int64, error) {
	row := q.queryRow(ctx, q.countProjectsByNodeStmt, countProjectsByNode, nodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, node_id, repo_url, branch, deploy_path, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	NodeID      int64          `json:"node_id"`
	RepoUrl     sql.NullString `json:"repo_url"`
	Branch      sql.NullString `json:"branch"`
	DeployPath  string         `json:"deploy_path"`
	Status      sql.NullString `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.createProjectStmt, createProject,
		arg.Name,
		arg.Description,
		arg.NodeID,
		arg.RepoUrl,
		arg.Branch,
		arg.DeployPath,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NodeID,
		&i.RepoUrl,
		&i.Branch,
		&i.DeployPath,
		&i.Status,
		&i.LastDeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteProjectStmt, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectStmt, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NodeID,
		&i.RepoUrl,
		&i.Branch,
		&i.DeployPath,
		&i.Status,
		&i.LastDeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectWithNode = `-- name: GetProjectWithNode :one
SELECT 
    p.id, p.name, p.description, p.node_id, p.repo_url, p.branch, p.deploy_path, p.status, p.last_deployed_at, p.created_at, p.updated_at,
    n.name as node_name,
    n.ip as node_ip
FROM projects p
LEFT JOIN nodes n ON p.node_id = n.id
WHERE p.id = ?
`

type GetProjectWithNodeRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	NodeID         int64          `json:"node_id"`
	RepoUrl        sql.NullString `json:"repo_url"`
	Branch         sql.NullString `json:"branch"`
	DeployPath     string         `json:"deploy_path"`
	Status         sql.NullString `json:"status"`
	LastDeployedAt sql.NullInt64  `json:"last_deployed_at"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	NodeName       sql.NullString `json:"node_name"`
	NodeIp         sql.NullString `json:"node_ip"`
}

func (q *Queries) GetProjectWithNode(ctx context.Context, id string) (GetProjectWithNodeRow, error) {
	row := q.queryRow(ctx, q.getProjectWithNodeStmt, getProjectWithNode, id)
	var i GetProjectWithNodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NodeID,
		&i.RepoUrl,
		&i.Branch,
		&i.DeployPath,
		&i.Status,
		&i.LastDeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NodeName,
		&i.NodeIp,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at FROM projects 
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsStmt, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NodeID,
			&i.RepoUrl,
			&i.Branch,
			&i.DeployPath,
			&i.Status,
			&i.LastDeployedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByNode = `-- name: ListProjectsByNode :many
SELECT id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at FROM projects 
WHERE node_id = ? 
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsByNodeParams struct {
	NodeID int64 `json:"node_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjectsByNode(ctx context.Context, arg ListProjectsByNodeParams) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsByNodeStmt, listProjectsByNode, arg.NodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NodeID,
			&i.RepoUrl,
			&i.Branch,
			&i.DeployPath,
			&i.Status,
			&i.LastDeployedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithNodes = `-- name: ListProjectsWithNodes :many
SELECT 
    p.id, p.name, p.description, p.node_id, p.repo_url, p.branch, p.deploy_path, p.status, p.last_deployed_at, p.created_at, p.updated_at,
    n.name as node_name,
    n.ip as node_ip
FROM projects p
LEFT JOIN nodes n ON p.node_id = n.id
ORDER BY p.created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsWithNodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProjectsWithNodesRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	NodeID         int64          `json:"node_id"`
	RepoUrl        sql.NullString `json:"repo_url"`
	Branch         sql.NullString `json:"branch"`
	DeployPath     string         `json:"deploy_path"`
	Status         sql.NullString `json:"status"`
	LastDeployedAt sql.NullInt64  `json:"last_deployed_at"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	NodeName       sql.NullString `json:"node_name"`
	NodeIp         sql.NullString `json:"node_ip"`
}

func (q *Queries) ListProjectsWithNodes(ctx context.Context, arg ListProjectsWithNodesParams) ([]ListProjectsWithNodesRow, error) {
	rows, err := q.query(ctx, q.listProjectsWithNodesStmt, listProjectsWithNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsWithNodesRow
	for rows.Next() {
		var i ListProjectsWithNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NodeID,
			&i.RepoUrl,
			&i.Branch,
			&i.DeployPath,
			&i.Status,
			&i.LastDeployedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NodeName,
			&i.NodeIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects 
SET name = ?,
    description = ?,
    repo_url = ?,
    branch = ?,
    deploy_path = ?,
    status = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	RepoUrl     sql.NullString `json:"repo_url"`
	Branch      sql.NullString `json:"branch"`
	DeployPath  string         `json:"deploy_path"`
	Status      sql.NullString `json:"status"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.updateProjectStmt, updateProject,
		arg.Name,
		arg.Description,
		arg.RepoUrl,
		arg.Branch,
		arg.DeployPath,
		arg.Status,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NodeID,
		&i.RepoUrl,
		&i.Branch,
		&i.DeployPath,
		&i.Status,
		&i.LastDeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectLastDeployed = `-- name: UpdateProjectLastDeployed :one
UPDATE projects 
SET last_deployed_at = strftime('%s', 'now'),
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at
`

func (q *Queries) UpdateProjectLastDeployed(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.updateProjectLastDeployedStmt, updateProjectLastDeployed, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NodeID,
		&i.RepoUrl,
		&i.Branch,
		&i.DeployPath,
		&i.Status,
		&i.LastDeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects 
SET status = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, name, description, node_id, repo_url, branch, deploy_path, status, last_deployed_at, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.queryRow(ctx, q.updateProjectStatusStmt, updateProjectStatus, arg.Status, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NodeID,
		&i.RepoUrl,
		&i.Branch,
		&i.DeployPath,
		&i.Status,
		&i.LastDeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
