// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: system_stat.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const insertSystemStats = `-- name: InsertSystemStats :exec
INSERT INTO system_stats (time, node_id, stat_type, cpu_id, value)
SELECT 
    unnest($1::timestamptz[]),
    unnest($2::int[]),
    unnest($3::text[]),
    unnest($4::int[]),
    unnest($5::double precision[])
`

type InsertSystemStatsParams struct {
	Column1 []time.Time `json:"column_1"`
	Column2 []int32     `json:"column_2"`
	Column3 []string    `json:"column_3"`
	Column4 []int32     `json:"column_4"`
	Column5 []float64   `json:"column_5"`
}

func (q *Queries) InsertSystemStats(ctx context.Context, arg InsertSystemStatsParams) error {
	_, err := q.exec(ctx, q.insertSystemStatsStmt, insertSystemStats,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
	)
	return err
}
