// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_stat.sql

package db

import (
	"context"
	"database/sql"
)

const getSystemStats = `-- name: GetSystemStats :many
select timestamp, value from system_stats ss 
where node_id = ? and stat_type = ?
and cpu_id = ?
and timestamp >= strftime('%s', 'now') - ?
`

type GetSystemStatsParams struct {
	NodeID   int64         `json:"node_id"`
	StatType string        `json:"stat_type"`
	CpuID    sql.NullInt64 `json:"cpu_id"`
	Column4  interface{}   `json:"column_4"`
}

type GetSystemStatsRow struct {
	Timestamp int64   `json:"timestamp"`
	Value     float64 `json:"value"`
}

func (q *Queries) GetSystemStats(ctx context.Context, arg GetSystemStatsParams) ([]GetSystemStatsRow, error) {
	rows, err := q.query(ctx, q.getSystemStatsStmt, getSystemStats,
		arg.NodeID,
		arg.StatType,
		arg.CpuID,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSystemStatsRow
	for rows.Next() {
		var i GetSystemStatsRow
		if err := rows.Scan(&i.Timestamp, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSystemStats = `-- name: InsertSystemStats :exec
INSERT INTO system_stats (timestamp, node_id, stat_type, cpu_id, value)
VALUES (?, ?, ?, ?, ?)
`

type InsertSystemStatsParams struct {
	Timestamp int64         `json:"timestamp"`
	NodeID    int64         `json:"node_id"`
	StatType  string        `json:"stat_type"`
	CpuID     sql.NullInt64 `json:"cpu_id"`
	Value     float64       `json:"value"`
}

func (q *Queries) InsertSystemStats(ctx context.Context, arg InsertSystemStatsParams) error {
	_, err := q.exec(ctx, q.insertSystemStatsStmt, insertSystemStats,
		arg.Timestamp,
		arg.NodeID,
		arg.StatType,
		arg.CpuID,
		arg.Value,
	)
	return err
}
